import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BrainCircuit, CalendarCheck, Check, LockKeyhole, Moon, ShieldCheck, Sparkles, TrendingDown } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { DemoBadge, Gauge, PageHeading, SectionTitle } from "@/components/freemind-shell";
import { chartColors, Stat, tooltipStyle } from "@/components/analytics-elements";

export const Route = createFileRoute("/analytics")({ head: () => ({ meta: [{ title: "Personnel Analytics | FreeMind" }, { name: "description", content: "Detailed synthetic early-warning analytics for personnel wellbeing and workload." }, { property: "og:title", content: "Personnel Analytics | FreeMind" }, { property: "og:description", content: "Detailed personnel stress, workload, sleep and recovery analytics." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Analytics });

const duty = [{ day: "Mon", hours: 8 },{ day: "Tue", hours: 10 },{ day: "Wed", hours: 9 },{ day: "Thu", hours: 11 },{ day: "Fri", hours: 8 },{ day: "Sat", hours: 10 },{ day: "Sun", hours: 6 }];
const sleep = [{ day: "Mon", hours: 6.3 },{ day: "Tue", hours: 5.8 },{ day: "Wed", hours: 7.2 },{ day: "Thu", hours: 6.1 },{ day: "Fri", hours: 6.7 },{ day: "Sat", hours: 7.3 },{ day: "Sun", hours: 7 }];
const stress = Array.from({ length: 30 }, (_, i) => ({ day: `${i + 1} Aug`, value: Math.round(40 + Math.sin(i / 2.6) * 7 - i * .25 + (i % 5 === 0 ? 5 : 0)) }));
const factors = [["Workload",72],["Sleep",61],["Duty Intensity",68],["Leave / Recovery",76],["Self-reported Wellness",82]] as const;
const checkData = [{ day:"Mon",mood:3.5,energy:3,fatigue:3.5,workload:4.2},{day:"Tue",mood:3.2,energy:2.8,fatigue:3.7,workload:4.4},{day:"Wed",mood:3.8,energy:3.1,fatigue:3.2,workload:4.1},{day:"Thu",mood:3.6,energy:3.2,fatigue:3.1,workload:4},{day:"Fri",mood:4,energy:3.5,fatigue:2.9,workload:3.9},{day:"Sat",mood:4.2,energy:3.7,fatigue:2.6,workload:3.6},{day:"Sun",mood:4.3,energy:3.8,fatigue:2.4,workload:3.5}];
const leave = [{m:"Apr",leave:2,recovery:61},{m:"May",leave:4,recovery:67},{m:"Jun",leave:1,recovery:60},{m:"Jul",leave:3,recovery:66},{m:"Aug",leave:4,recovery:72}];

function Analytics() {
  const [period, setPeriod] = useState("Last 30 Days");
  const [recommendationsOpen, setRecommendationsOpen] = useState(false);
  return <><PageHeading eyebrow="Predictive welfare monitoring" title="Personnel Analytics" description="Your personalized wellbeing and workload insights" actions={<div className="flex flex-wrap items-center gap-3"><DemoBadge /><div className="flex rounded-lg border border-border bg-card p-1">{["Last 7 Days","Last 30 Days","Last 3 Months"].map(p => <Button key={p} size="sm" variant={period === p ? "default" : "ghost"} onClick={() => setPeriod(p)}>{p}</Button>)}</div><span className="text-xs text-muted-foreground">Updated 17 Sep, 08:10</span></div>} />
    <Card className="border-primary/20 p-6 shadow-soft md:p-8"><div className="grid gap-8 lg:grid-cols-[auto_1fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-primary">AI wellbeing overview</p><h2 className="mt-2 font-display text-2xl font-bold">Overall Wellbeing Risk Indicator</h2><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">Current indicators suggest relatively stable wellbeing with some workload-related pressure.</p><p className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-muted-foreground"><BrainCircuit className="size-4 text-primary" />AI-generated early warning indicator — not a medical diagnosis.</p></div><Gauge value={78} /><div className="space-y-4">{factors.map(([label,value]) => <div key={label}><div className="mb-1.5 flex justify-between text-xs font-semibold"><span>{label}</span><span>{value}%</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${value}%` }} /></div></div>)}</div></div></Card>
    <section className="mt-7"><SectionTitle title="Stress Indicator — Last 30 Days" description="Synthetic early-warning trend, not a clinical measure" /><div className="grid gap-5 xl:grid-cols-[1.65fr_1fr]"><Card className="p-5 shadow-soft"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={stress}><defs><linearGradient id="stressFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={chartColors.stress} stopOpacity={.28}/><stop offset="1" stopColor={chartColors.stress} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" stroke={chartColors.grid} vertical={false}/><XAxis dataKey="day" interval={5} tick={{fontSize:11,fill:chartColors.text}} axisLine={false}/><YAxis domain={[0,60]} tick={{fontSize:11,fill:chartColors.text}} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="value" stroke={chartColors.stress} fill="url(#stressFill)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></Card><Card className="p-6 shadow-soft"><div className="grid grid-cols-3 gap-3"><Stat label="Current" value="32%" /><Stat label="Previous week" value="40%" /><Stat label="Change" value="-8%" /></div><div className="mt-6 flex gap-3 rounded-lg bg-success-soft p-4"><TrendingDown className="size-5 shrink-0 text-success"/><p className="text-sm leading-6">Your stress indicator has decreased over the past week, while workload remains moderately high.</p></div></Card></div></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-2">
      <Card className="p-6 shadow-soft"><SectionTitle title="Workload Analysis" description="Duty hours · Last 7 days"/><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={duty}><CartesianGrid strokeDasharray="4 4" stroke={chartColors.grid} vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="hours" fill={chartColors.workload} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Average Daily Duty" value="8.9 hrs"/><Stat label="Weekly Duty" value="62 hrs"/><Stat label="Night Duties" value="3"/><Stat label="Consecutive Days" value="5"/></div><p className="mt-4 text-sm text-muted-foreground">Workload pattern indicates increased duty intensity during the middle of the week.</p></Card>
      <Card className="p-6 shadow-soft"><SectionTitle title="Sleep & Recovery" description="Rest duration · Last 7 days"/><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={sleep}><CartesianGrid strokeDasharray="4 4" stroke={chartColors.grid} vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis domain={[4,9]} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle}/><Line type="monotone" dataKey="hours" stroke={chartColors.sleep} strokeWidth={3} dot={{r:4}}/></LineChart></ResponsiveContainer></div><div className="grid grid-cols-3 gap-3"><Stat label="Average Sleep" value="6h 38m"/><Stat label="Recovery Score" value="68%"/><Stat label="Consistency" value="74%"/></div><p className="mt-4 flex gap-2 text-sm text-muted-foreground"><Moon className="size-4 text-primary"/>Sleep duration has improved over the last 3 days.</p></Card>
    </section>
    <section className="mt-7"><SectionTitle title="Duty & Deployment Analytics" /><div className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><Card className="p-6 shadow-soft"><div className="grid grid-cols-2 gap-3"><Stat label="Current Deployment" value="Field Operations"/><Stat label="Duration" value="18 days"/><Stat label="Night Duties" value="4 this month"/><Stat label="Training" value="2 done / 1 upcoming"/></div><div className="mt-6 grid grid-cols-[150px_1fr] items-center gap-4"><div className="h-36"><ResponsiveContainer><PieChart><Pie data={[{name:"Field",value:46},{name:"Station",value:32},{name:"Training",value:12},{name:"Leave",value:10}]} dataKey="value" innerRadius={42} outerRadius={62} paddingAngle={3}>{[chartColors.workload,chartColors.recovery,chartColors.stress,chartColors.sleep].map(c=><Cell key={c} fill={c}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/></PieChart></ResponsiveContainer></div><div className="space-y-2 text-sm"><p><b>46%</b> Field deployment</p><p><b>32%</b> Station duty</p><p><b>12%</b> Training commitments</p><p><b>10%</b> Leave / recovery</p></div></div></Card><Card className="p-6 shadow-soft"><SectionTitle title="Operational Commitments" description="Frequency across the current period"/><div className="h-64"><ResponsiveContainer><BarChart data={[{type:"Deployments",value:6},{type:"Night shifts",value:4},{type:"Transfers",value:1},{type:"Training",value:3},{type:"Consecutive",value:5}]} layout="vertical"><CartesianGrid strokeDasharray="4 4" stroke={chartColors.grid} horizontal={false}/><XAxis type="number" axisLine={false}/><YAxis dataKey="type" type="category" width={90} axisLine={false} tickLine={false} tick={{fontSize:11}}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="value" fill={chartColors.recovery} radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></Card></div></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-2"><Card className="p-6 shadow-soft"><SectionTitle title="Leave & Recovery Pattern" description="Monthly leave usage and recovery trend"/><div className="h-60"><ResponsiveContainer><BarChart data={leave}><CartesianGrid strokeDasharray="4 4" stroke={chartColors.grid} vertical={false}/><XAxis dataKey="m" axisLine={false}/><YAxis yAxisId="l" axisLine={false}/><YAxis yAxisId="r" orientation="right" domain={[50,80]} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Bar yAxisId="l" dataKey="leave" fill={chartColors.workload} radius={[4,4,0,0]}/><Line yAxisId="r" type="monotone" dataKey="recovery" stroke={chartColors.recovery}/></BarChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Leave Used" value="4 days"/><Stat label="Remaining" value="12 days"/><Stat label="Avg. Break" value="1.6 days"/><Stat label="Recovery Trend" value="Improving"/></div></Card><Card className="p-6 shadow-soft"><SectionTitle title="Voluntary Wellness Check-ins" description="Based on voluntary self-reported wellness inputs · 1–5 scale"/><div className="h-60"><ResponsiveContainer><LineChart data={checkData}><CartesianGrid strokeDasharray="4 4" stroke={chartColors.grid} vertical={false}/><XAxis dataKey="day" axisLine={false}/><YAxis domain={[1,5]} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Line dataKey="mood" stroke={chartColors.recovery} strokeWidth={2}/><Line dataKey="energy" stroke={chartColors.sleep} strokeWidth={2}/><Line dataKey="fatigue" stroke={chartColors.stress} strokeWidth={2}/><Line dataKey="workload" stroke={chartColors.workload} strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Mood" value="4.1 / 5"/><Stat label="Energy" value="3.4 / 5"/><Stat label="Fatigue" value="2.8 / 5"/><Stat label="Workload Perception" value="3.9 / 5"/></div></Card></section>
    <section className="mt-7"><Card className="border-primary/25 bg-accent p-6 shadow-soft"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-primary"><Sparkles className="size-4"/>AI-generated insights</p><h2 className="mt-2 font-display text-2xl font-bold">Early signals worth reviewing</h2></div><Button onClick={() => setRecommendationsOpen(true)}>View Recommendations</Button></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{["Workload has increased by 14% compared with your recent baseline.","Night duty frequency has increased during the current period.","Sleep duration is slightly below your recent personal average.","Recent wellness check-ins indicate improving mood."].map((x,i)=><div key={x} className="rounded-lg border border-primary/15 bg-card p-4"><span className="text-xs font-bold text-primary">0{i+1}</span><p className="mt-2 text-sm leading-6">{x}</p></div>)}</div></Card></section>
    {recommendationsOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/40 p-5" role="dialog" aria-modal="true" aria-labelledby="recommendations-title" onClick={() => setRecommendationsOpen(false)}><Card className="w-full max-w-lg p-6 shadow-soft" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><h2 id="recommendations-title" className="font-display text-xl font-bold">Supportive Recommendations</h2><p className="mt-1 text-sm text-muted-foreground">Non-medical guidance based on synthetic wellbeing indicators.</p></div><Button variant="ghost" size="icon" aria-label="Close recommendations" onClick={() => setRecommendationsOpen(false)}>×</Button></div><ul className="mt-6 space-y-4 text-sm">{["Consider scheduling adequate recovery time after consecutive duties.","Review workload distribution with the appropriate supervisor if required.","Maintain regular voluntary wellness check-ins.","Access available organizational wellness resources."].map(x=><li key={x} className="flex gap-2"><Check className="size-4 shrink-0 text-primary"/>{x}</li>)}</ul></Card></div>}
    <section className="mt-7"><Card className="border-border p-6 shadow-soft"><div className="flex gap-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-lg bg-accent text-primary"><LockKeyhole/></div><div className="flex-1"><h2 className="font-display text-xl font-bold">Your Privacy Matters</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{["Wellness inputs are voluntary","Data is encrypted","Personal identifiers are minimized","Role-based access control","Analytics support early intervention, not diagnosis","Officers can access their own personal analytics"].map(x=><p key={x} className="flex gap-2 text-sm"><ShieldCheck className="size-4 shrink-0 text-success"/>{x}</p>)}</div></div></div></Card></section>
  </>;
}